backend:
  name: git-gateway
  repo: banhae/blog
media_folder: static/assets
public_folder: /assets
collections:
  - name: etc
    label: Etc
    folder: blog/etc
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: category, label: Category }
      - { name: body, label: Body, widget: markdown }
  - name: react
    label: React
    folder: blog/react
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: category, label: Category }
      - { name: body, label: Body, widget: markdown }
  - name: blog
    label: Blog
    folder: blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
